# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab88c7ea5e9debe4eb10014a44387dd843edadd545e8eaa411444123a75237a0b3852179af84b1e97853c3134f66cd2e4e0041f7663d5fe105112768faa8524

test:
  secret_key_base: 9a31681aeb6df0713705f0f4d147f8b9c4df8844b6d9421a3c09f4d90eccaeac75830fd3f40ad6a68af1deb8a94d57d4721faf29926c844459231f986dd17d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
